name: Build and test folder organized Java and go apps

on: [push, pull_request]

jobs:
  Java:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          javaApps: [java-apps/test, java-apps/HelloWorld]
    defaults:
        run:
            working-directory: ${{ matrix.javaApps }}
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Install
          run: mvn clean install
        - name: Build
          run: mvn package
        - name: Test
          run: mvn test
  go:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            goApps: [go-apps/go/hello, go-apps/go/hello2]
    defaults:
        run:
            working-directory: ${{ matrix.goApps }}
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: '1.13.1'
        - name: Test go version
          run: go version
        - name: Get dependencies
          run: go get 
        - name: Test DryRun
          run: go test -v -ginkgo.noColor -ginkgo.dryRun
        - name: Test DryRun
          run: go test -v -ginkgo.noColor
        - name: Notify slack success
          if: success()
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: voxmedia/github-action-slack-notify-build@v1
          with:
            channel: builds
            status: SUCCESS
            color: good
        - name: Notify slack fail
          if: failure()
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: voxmedia/github-action-slack-notify-build@v1
          with:
            channel: builds
            status: FAILED
            color: danger
#  slack-notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Slack Notification
#        uses: rtCamp/action-slack-notify@master
#        env:
#          SLACK_CHANNEL: builds
#          SLACK_COLOR: '#3278BD'
#          SLACK_ICON: https://github.com/ruben-rodriguez.png?size=48
#          SLACK_MESSAGE: 'Post Content :rocket:'
#          SLACK_TITLE: Post Title
#          SLACK_USERNAME: GitHub Build
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
