name: Build and test folder organized Java and go apps

on: [push, pull_request]

jobs:
  Java:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          javaApps: [java-apps/test, java-apps/HelloWorld]
    defaults:
        run:
            working-directory: ${{ matrix.javaApps }}
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Load and print env variable
          run: |
            export $(grep -v '#.*' .env | xargs)
            echo $TEST
        - name: Install
          run: |
            export $(grep -v '#.*' .env | xargs)
            mvn clean install
        - name: Build
          run: |
            export $(grep -v '#.*' .env | xargs)
            mvn package
        - name: Test
          run: |
            export $(grep -v '#.*' .env | xargs)
            mvn test
        - name: Install git-secrets & reveal a secret
          env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          run: |
            echo $GPG_PRIVATE_KEY | tr ',' '\n' > ./private_key.gpg
            gpg --import ./private_key.gpg
            echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
            wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
            sudo apt-get update && sudo apt-get install git-secret
            git secret reveal
            cat ../../secrets/secret
  go:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            goApps: [go-apps/go/hello, go-apps/go/hello2]
    defaults:
        run:
            working-directory: ${{ matrix.goApps }}
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: '1.13.1'
        - name: Test go version
          run: go version
        - name: Get dependencies
          run: go get 
        - name: Test DryRun
          run: go test -v -ginkgo.noColor -ginkgo.dryRun
        - name: Test
          run: go test -v -ginkgo.noColor
        - name: Notify slack success
          if: success()
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: voxmedia/github-action-slack-notify-build@v1
          with:
            channel: builds
            status: SUCCESS
            color: good
        - name: Notify slack fail
          if: failure()
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: voxmedia/github-action-slack-notify-build@v1
          with:
            channel: builds
            status: FAILED
            color: danger
            
  build-java:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build Java apps
    needs: Java
    steps:
      - name: Check build matrix status
        if: ${{ needs.Java.result != 'success' }}
        run: exit 1
  build-go:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build go apps
    needs: go
    steps:
      - name: Check build matrix status
        if: ${{ needs.go.result != 'success' }}
        run: exit 1